#!/usr/bin/env ruby
# Compare music libraries. Find files on source missing from target.
#
#   ruby music_diff.rb                          # report only (default)
#   ruby music_diff.rb --script                 # also write copy_missing.sh
#   ruby music_diff.rb --source /other/path     # override source
#   ruby music_diff.rb --target /other/path     # override target

require "fileutils"

TARGET  = "/Volumes/Music/Music"
SOURCES = [
  "/Volumes/LaCie/Music/iTunes/iTunes Media/Music",
  "/Volumes/LaCie/Music/to import",
]
HOLDING = "/Volumes/Music/Music/_holding"
AUDIO   = %w[.mp3 .m4a .m4p .aac .flac .wav .aiff .ogg .wma].freeze

def normalize(name)
  n = name.encode("UTF-8", invalid: :replace, undef: :replace)
  n = n.unicode_normalize(:nfkd).encode("ASCII", fallback: ->(_) { "" })
  n.downcase.gsub(/[^a-z0-9]/, "").sub(/\Athe/, "")
end

def normalize_file(name)
  ext = File.extname(name).downcase
  base = AUDIO.include?(ext) ? File.basename(name, File.extname(name)) : name
  normalize(base)
end

require "shellwords"
def shellescape(s) = Shellwords.shellescape(s)

# Scan a music root into { norm_artist => { orig:, albums: { norm_album => { orig:, files: { norm_file => orig } } } } }
def scan(root)
  lib = {}
  Dir.children(root).each do |artist|
    next if artist.start_with?(".")
    albums_path = "#{root}/#{artist}"
    artist_albums = Dir.children(albums_path) rescue next
    na = normalize(artist)
    lib[na] ||= { orig: artist, albums: {} }

    artist_albums.each do |album|
      next if album.start_with?(".")
      files_path = "#{albums_path}/#{album}"
      album_files = Dir.children(files_path) rescue next
      nal = normalize(album)
      lib[na][:albums][nal] ||= { orig: album, files: {} }

      album_files.each do |file|
        next unless AUDIO.include?(File.extname(file).downcase)
        lib[na][:albums][nal][:files][normalize_file(file)] = file
      end
    end
  end
  lib
end

# --- Main ---

script_mode = ARGV.delete("--script")
si = ARGV.index("--source"); custom_src = si ? (ARGV.delete_at(si); [ARGV.delete_at(si)]) : nil
ti = ARGV.index("--target"); target_dir = ti ? (ARGV.delete_at(ti); ARGV.delete_at(ti)) : TARGET
source_dirs = custom_src || SOURCES
script_path = File.expand_path("copy_missing.sh", __dir__)

puts "Target: #{target_dir}"
puts "Source: #{source_dirs.join(', ')}"
puts "Mode:   #{script_mode ? "report + write #{script_path}" : 'report only (use --script to write copy commands)'}"
puts

abort "ERROR: Target not found: #{target_dir}" unless File.directory?(target_dir)

puts "Scanning target..."
target = scan(target_dir)
t_a = target.size
t_al = target.values.sum { |a| a[:albums].size }
t_f = target.values.sum { |a| a[:albums].values.sum { |al| al[:files].size } }
puts "  #{t_a} artists, #{t_al} albums, #{t_f} files"
puts

script_out = script_mode ? File.open(script_path, "w") : nil
script_out&.puts "#!/bin/bash\n# Generated by music_diff.rb\n"

source_dirs.each do |src_dir|
  unless File.directory?(src_dir)
    puts "SKIP: #{src_dir} not found"
    next
  end

  puts "Scanning #{src_dir}..."
  source = scan(src_dir)
  s_a = source.size
  s_al = source.values.sum { |a| a[:albums].size }
  s_f = source.values.sum { |a| a[:albums].values.sum { |al| al[:files].size } }
  puts "  #{s_a} artists, #{s_al} albums, #{s_f} files"

  missing = { artist: [], album: [], file: [] }
  matched = { artists: 0, albums: 0, files: 0 }

  source.each do |na, src_artist|
    unless target[na]
      src_artist[:albums].each_value do |al|
        al[:files].each_value { |f| missing[:artist] << [src_artist[:orig], al[:orig], f] }
      end
      next
    end
    matched[:artists] += 1
    tgt_artist = target[na]

    src_artist[:albums].each do |nal, src_album|
      unless tgt_artist[:albums][nal]
        src_album[:files].each_value { |f| missing[:album] << [src_artist[:orig], src_album[:orig], f] }
        next
      end
      matched[:albums] += 1
      tgt_album = tgt_artist[:albums][nal]

      src_album[:files].each do |nf, file|
        if tgt_album[:files][nf]
          matched[:files] += 1
        else
          missing[:file] << [src_artist[:orig], src_album[:orig], file]
        end
      end
    end
  end

  puts
  puts "Matched: #{matched[:artists]} artists, #{matched[:albums]} albums, #{matched[:files]} files"

  total = missing.values.sum(&:size)
  if total == 0
    puts "All files accounted for."
    puts
    next
  end

  if missing[:artist].any?
    grouped = missing[:artist].group_by { |a, _, _| a }
    puts "\n--- Missing artists (#{grouped.size} artists, #{missing[:artist].size} files) ---"
    grouped.each do |artist, files|
      by_album = files.group_by { |_, al, _| al }
      puts "  #{artist}/"
      by_album.each { |album, af| puts "    #{album}/ (#{af.size} files)" }
    end
  end

  if missing[:album].any?
    grouped = missing[:album].group_by { |a, _, _| a }
    puts "\n--- Missing albums (known artist) (#{missing[:album].size} files) ---"
    grouped.each do |artist, files|
      na = normalize(artist)
      tgt_albums = target[na][:albums].values.map { |a| a[:orig] }.sort
      by_album = files.group_by { |_, al, _| al }
      puts "  #{artist}/"
      by_album.each { |album, af| puts "    - #{album}/ (#{af.size} files)  << MISSING" }
      tgt_albums.each { |a| puts "    + #{a}/" }
    end
  end

  if missing[:file].any?
    grouped = missing[:file].group_by { |a, al, _| [a, al] }
    puts "\n--- Missing files (known album) (#{missing[:file].size} files) ---"
    grouped.each do |(artist, album), files|
      na = normalize(artist)
      nal = normalize(album)
      tgt_files = target[na][:albums][nal][:files].values.sort
      puts "  #{artist}/#{album}/"
      puts "    source has #{files.size} extra:"
      files.first(20).each { |_, _, f| puts "      - #{f}" }
      puts "      ... and #{files.size - 20} more" if files.size > 20
      if tgt_files.any?
        puts "    target has #{tgt_files.size}:"
        tgt_files.first(10).each { |f| puts "      + #{f}" }
        puts "      ... and #{tgt_files.size - 10} more" if tgt_files.size > 10
      end
    end
  end

  if script_out
    puts "\nWriting #{total} copy commands to #{script_path}"
    missing.values.flatten(1).each do |artist, album, file|
      dest = File.join(HOLDING, artist, album)
      script_out.puts %(mkdir -p #{shellescape(dest)})
      script_out.puts %(cp #{shellescape(File.join(src_dir, artist, album, file))} #{shellescape(File.join(dest, file))})
    end
  end
  puts
end

if script_out
  script_out.close
  puts "Run when ready:  bash #{script_path}"
end
